CREATE SCHEMA IF NOT EXISTS public;

DROP SCHEMA IF EXISTS starcedu_auth CASCADE;
DROP EXTENSION IF EXISTS pgcrypto;
CREATE SCHEMA starcedu_auth;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
ALTER EXTENSION pgcrypto SET SCHEMA public;